manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: stephen
      url-base: https://github.com/stephen
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: xwu
      url-base: https://github.com/xwu
  projects:
    - name: zmk
      # remote: stephen
      # revision: stephen/split-encoder
      remote: petejohanson
      revision: ble/defer-connection-param-upgarade-while-pairing
      # revision: ble/hog-characteristic-perm-tweaks-macos
      # remote: xwu
      # revision: macos-pairing
      import: app/west.yml
  self:
    path: config
