manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/stephen
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: stephen/split-encoder
      import: app/west.yml
  self:
    path: config
